name: Daily Commit (Push + Cron)

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  keep_green:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # important for pushing

      - name: Debug Start
        run: echo "Workflow started at $(date)"

      - name: Update daily log
        run: |
          touch daily_log.txt
          echo "$(date): Daily commit" >> daily_log.txt
          git config --global user.name "swopnilll"
          git config --global user.email "swopnilacharya@gmail.com"
          git add daily_log.txt
          git commit -m "Auto-update: $(date)" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/swopnilll/daily-challenge.git HEAD:main
