name: Daily Commit (Push + Cron)

on:
  push:
    branches:
      - main             # Run workflow on any push to main
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes (adjust later)
  workflow_dispatch:        # Allows manual trigger too

jobs:
  keep_green:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Debug Start
        run: echo "Workflow started at $(date)"

      - name: Update daily log
        run: |
          # Create the log file if it doesn't exist
          touch daily_log.txt

          # Append date to log
          echo "$(date): Daily commit" >> daily_log.txt

          # Git commit and push
          git config --global user.name "swopnilll"
          git config --global user.email "swopnilacharya@gmail.com"
          git add daily_log.txt
          git commit -m "Auto-update: $(date)" || echo "Nothing to commit"
          git push
